service: ai-scheme-assistant

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  timeout: 15

  environment:
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::ai-scheme-rules-maharashtra-ai-for-bharat
            - arn:aws:s3:::ai-scheme-rules-maharashtra-ai-for-bharat/*

        - Effect: Allow
          Action:
            - bedrock:InvokeModel
          Resource: "*"

functions:
  app:
    handler: lambda.handler
    events:
      - httpApi:
          path: /evaluate
          method: post